MyBlogMain/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('app_auth.urls')),
    path('', include('app_post.urls')),
    path('like/', include('app_like.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_auth/urls.py
from django.urls import path
from .views import change_pro_pic, login_page, logout_user, pass_change, profile, sign_up_view, user_change

app_name = "app_auth"

urlpatterns = [
    path('signup/', sign_up_view, name="signup"),
    path('login/', login_page, name='login'),
    path('logout/', logout_user, name='logout'),
    path('profile/', profile, name='profile'),
    path('change-profile/', user_change, name='user_change'),
    path('password/', pass_change, name='pass_change'),
    path('add-picture/', change_pro_pic, name='add_pro_pic'),
    path('change-picture/', change_pro_pic, name='change_pro_pic'),
]

app_post/urls.py
from .views import CreatePost, MyPosts, UpdatePost, post_details, PostList
from django.urls import path

app_name="app_post"

urlpatterns = [
    path('', PostList.as_view(), name='post_list'),
    path('details/<slug:slug>', post_details, name='post_details'),
    path('write/', CreatePost.as_view(), name='create_post'),
    path('my-blogs/', MyPosts.as_view(), name='my_blogs'),
    path('edit/<pk>/', UpdatePost.as_view(), name='edit_blog'),
]

app_auth/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.


def user_img_path(instance, filename):
    return f'profile_pictures/{instance.user}/{filename}'


class UserProfile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name="user_profile")
    profile_picture = models.ImageField(
        upload_to=user_img_path, blank=True, null=True)
    
    def __str__(self):
        return f"{self.user.username}"


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


def save_user_profile(sender, instance, **kwargs):
    instance.user_profile.save()


post_save.connect(create_user_profile, sender=User)
post_save.connect(save_user_profile, sender=User)

app_auth/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from .models import UserProfile


User = get_user_model()


class SignUpForm(UserCreationForm):
    email = forms.EmailField(label="Email Address", required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserProfileChange(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password')


class ProfilePic(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('profile_picture',)

app_auth/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.urls.base import reverse
from .forms import ProfilePic, SignUpForm, UserProfileChange
from django.contrib.auth.decorators import login_required

# Create your views here.


def sign_up_view(request):
    form = SignUpForm()
    registered = False
    if request.method == "POST":
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            registered = True
    dict = {
        "form": form,
        "registered": registered,
    }
    return render(request, "app_auth/signup.html", context=dict)


def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('app_post:post_list'))
    return render(request, 'app_auth/login.html', context={'form': form})


@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('app_post:post_list'))


@login_required
def profile(request):
    return render(request, 'app_auth/profile.html', context={})


@login_required
def user_change(request):
    current_user = request.user
    form = UserProfileChange(instance=current_user)
    if request.method == 'POST':
        form = UserProfileChange(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            form = UserProfileChange(instance=current_user)
    return render(request, 'app_auth/change_profile.html', context={'form': form})


@login_required
def pass_change(request):
    current_user = request.user
    changed = False
    form = PasswordChangeForm(current_user)
    if request.method == 'POST':
        form = PasswordChangeForm(current_user, data=request.POST)
        if form.is_valid():
            form.save()
            changed = True
    return render(request, 'app_auth/pass_change.html', context={'form': form, 'changed': changed})



@login_required
def change_pro_pic(request):
    form = ProfilePic(instance=request.user.user_profile)
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES,
                          instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('app_auth:profile'))
    return render(request, 'app_auth/pro_pic_add.html', context={'form': form})

app_auth/templates/app_auth/login.html
{% extends 'auth_base.html' %}
{% load tailwind_filters %}
{% block title %}Login{% endblock title %}
{% block content %}
    <div class="my-4 flex flex-col">
        <div class="container max-w-sm mx-auto flex-1 flex flex-col items-center justify-center px-2">
            <div class="bg-gray-100 px-3 rounded shadow-md text-black-900 w-full">
                <h1 class="mb-8 text-3xl text-center">Login To Your Account</h1>
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button
                    type="submit"
                    class="w-full text-center py-1 rounded bg-pink-400 hover:bg-pink-600 focus:outline-none my-1"
                    >Login</button>
                </form>

                <div class="text-center text-sm text-grey-dark my-2">
                    <div class="text-grey-dark mt-2">
                        Don't have an account? 
                        <a href="{% url 'app_auth:signup' %}">
                            <button class="bg-purple-500 hover:bg-blue-700 text-white font-bold py-1 px-2 rounded">
                                Signup
                            </button>
                        </a>
                    </div>
                    <div class="text-grey-dark mt-2">
                        Back to
                        <a href="{% url 'app_post:post_list' %}">
                            <button class="bg-green-500 hover:bg-blue-700 text-white font-bold py-1 px-2 rounded">
                                Home
                            </button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

app_auth/templates/app_auth/pass_change.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block title %}Change Password{% endblock title %}
{% block content %}
    {% if changed %}
        <div class="bg-green-100 border border-green-400 text-black-700 px-4 py-3 rounded relative mx-7" role="alert">
            <strong class="font-bold">Password Changed</strong>
            <span class="block sm:inline">
                Login Now by 
                <a href="{% url 'app_auth:login' %}">
                    <button class="bg-purple-500 hover:bg-blue-700 text-white font-bold py-1 px-2 rounded">
                        Clicking here
                    </button>
                </a>
            </span>
            <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
                <svg class="fill-current h-6 w-6 text-red-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
            </span>
        </div>
    {% else %}
        <div class="min-h-screen flex flex-col mb-4">
            <div class="container max-w-sm mx-auto flex-1 flex flex-col items-center justify-center px-2">
                <div class="bg-gray-100 px-3 rounded shadow-md text-black-900 w-full">
                    <h1 class="mb-8 text-3xl text-center">Change Your Password</h1>
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button
                        type="submit"
                        class="w-full text-center py-1 rounded bg-pink-400 hover:bg-pink-600 focus:outline-none my-1"
                        >Change</button>
                    </form>

                    <div class="text-center text-sm text-grey-dark my-2">
                        <div class="text-grey-dark mt-2">
                            Back to
                            <a href="{% url 'app_auth:profile' %}">
                                <button class="bg-green-500 hover:bg-blue-700 text-white font-bold py-1 px-2 rounded">
                                    Profile
                                </button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock content %}

app_auth/templates/app_auth/profile.html
{% extends 'base.html' %}
{% block title %} {{ user.username }} {% endblock title %}
{% block content %}
    <div class="font-sans antialiased text-gray-900 leading-normal tracking-wider bg-cover" style="background-image:url('https://source.unsplash.com/1L71sPT5XKc');">
        <div class="max-w-4xl flex items-center h-auto lg:h-screen flex-wrap mx-auto my-32 lg:my-0">
            <div id="profile" class="w-full lg:w-3/5 rounded-lg lg:rounded-l-lg lg:rounded-r-none shadow-2xl bg-white opacity-75 mx-6 lg:mx-0">
                <div class="p-4 md:p-12 text-center lg:text-left">
                    <div class="block lg:hidden rounded-full shadow-xl mx-auto -mt-16 h-48 w-48 bg-cover bg-center" style="background-image: url('https://source.unsplash.com/MP0IUfwrn0A')"></div>
                    <h1 class="text-3xl font-bold pt-8 lg:pt-0">
                        {% if user.first_name and user.last_name %}
                            {{user.first_name }} {{ user.last_name }} (@{{ user.username }})
                        {% else %}
                            @{{ user.username }}
                        {% endif %}
                    </h1>
                    <div class="mx-auto lg:mx-0 w-4/5 pt-3 border-b-2 border-green-500 opacity-25"></div>
                    <p class="pt-4 text-base font-bold flex items-center justify-center lg:justify-start">
                        <svg class="h-4 fill-current text-green-700 pr-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9 12H1v6a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-6h-8v2H9v-2zm0-1H0V5c0-1.1.9-2 2-2h4V2a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v1h4a2 2 0 0 1 2 2v6h-9V9H9v2zm3-8V2H8v1h4z"/></svg>
                        What you do
                    </p>
                    <p class="pt-2 text-gray-600 text-xs lg:text-sm flex items-center justify-center lg:justify-start">
                        <svg class="h-4 fill-current text-green-700 pr-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M10 20a10 10 0 1 1 0-20 10 10 0 0 1 0 20zm7.75-8a8.01 8.01 0 0 0 0-4h-3.82a28.81 28.81 0 0 1 0 4h3.82zm-.82 2h-3.22a14.44 14.44 0 0 1-.95 3.51A8.03 8.03 0 0 0 16.93 14zm-8.85-2h3.84a24.61 24.61 0 0 0 0-4H8.08a24.61 24.61 0 0 0 0 4zm.25 2c.41 2.4 1.13 4 1.67 4s1.26-1.6 1.67-4H8.33zm-6.08-2h3.82a28.81 28.81 0 0 1 0-4H2.25a8.01 8.01 0 0 0 0 4zm.82 2a8.03 8.03 0 0 0 4.17 3.51c-.42-.96-.74-2.16-.95-3.51H3.07zm13.86-8a8.03 8.03 0 0 0-4.17-3.51c.42.96.74 2.16.95 3.51h3.22zm-8.6 0h3.34c-.41-2.4-1.13-4-1.67-4S8.74 3.6 8.33 6zM3.07 6h3.22c.2-1.35.53-2.55.95-3.51A8.03 8.03 0 0 0 3.07 6z"/></svg>
                        Username: {{ user.username }}
                    </p>
                    <p class="pt-2 text-gray-600 text-xs lg:text-sm flex items-center justify-center lg:justify-start">
                        <svg class="h-4 fill-current text-green-700 pr-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M10 20a10 10 0 1 1 0-20 10 10 0 0 1 0 20zm7.75-8a8.01 8.01 0 0 0 0-4h-3.82a28.81 28.81 0 0 1 0 4h3.82zm-.82 2h-3.22a14.44 14.44 0 0 1-.95 3.51A8.03 8.03 0 0 0 16.93 14zm-8.85-2h3.84a24.61 24.61 0 0 0 0-4H8.08a24.61 24.61 0 0 0 0 4zm.25 2c.41 2.4 1.13 4 1.67 4s1.26-1.6 1.67-4H8.33zm-6.08-2h3.82a28.81 28.81 0 0 1 0-4H2.25a8.01 8.01 0 0 0 0 4zm.82 2a8.03 8.03 0 0 0 4.17 3.51c-.42-.96-.74-2.16-.95-3.51H3.07zm13.86-8a8.03 8.03 0 0 0-4.17-3.51c.42.96.74 2.16.95 3.51h3.22zm-8.6 0h3.34c-.41-2.4-1.13-4-1.67-4S8.74 3.6 8.33 6zM3.07 6h3.22c.2-1.35.53-2.55.95-3.51A8.03 8.03 0 0 0 3.07 6z"/></svg>
                        Email: {{ user.email }}
                    </p>
                    <p class="pt-8 text-sm">
                        Totally optional short description about yourself, what you do and so on.
                    </p>
                    <a href="{% url 'app_auth:user_change' %}" class="pt-12 pb-8">
                        <button class="bg-green-700 hover:bg-green-900 text-white font-bold py-2 px-4 rounded-full">
                        Edit Your Data
                        </button> 
                    </a>
                    <div class="mt-6 pb-16 lg:pb-0 w-4/5 lg:w-full mx-auto flex flex-wrap items-center justify-between">
                        <a class="link" href="#" data-tippy-content="@facebook_handle">
                            <svg class="h-6 fill-current text-gray-600 hover:text-green-700" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Facebook</title><path d="M22.676 0H1.324C.593 0 0 .593 0 1.324v21.352C0 23.408.593 24 1.324 24h11.494v-9.294H9.689v-3.621h3.129V8.41c0-3.099 1.894-4.785 4.659-4.785 1.325 0 2.464.097 2.796.141v3.24h-1.921c-1.5 0-1.792.721-1.792 1.771v2.311h3.584l-.465 3.63H16.56V24h6.115c.733 0 1.325-.592 1.325-1.324V1.324C24 .593 23.408 0 22.676 0"/></svg>
                        </a>
                        <a class="link" href="#" data-tippy-content="@twitter_handle">
                            <svg class="h-6 fill-current text-gray-600 hover:text-green-700" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Twitter</title><path d="M23.954 4.569c-.885.389-1.83.654-2.825.775 1.014-.611 1.794-1.574 2.163-2.723-.951.555-2.005.959-3.127 1.184-.896-.959-2.173-1.559-3.591-1.559-2.717 0-4.92 2.203-4.92 4.917 0 .39.045.765.127 1.124C7.691 8.094 4.066 6.13 1.64 3.161c-.427.722-.666 1.561-.666 2.475 0 1.71.87 3.213 2.188 4.096-.807-.026-1.566-.248-2.228-.616v.061c0 2.385 1.693 4.374 3.946 4.827-.413.111-.849.171-1.296.171-.314 0-.615-.03-.916-.086.631 1.953 2.445 3.377 4.604 3.417-1.68 1.319-3.809 2.105-6.102 2.105-.39 0-.779-.023-1.17-.067 2.189 1.394 4.768 2.209 7.557 2.209 9.054 0 13.999-7.496 13.999-13.986 0-.209 0-.42-.015-.63.961-.689 1.8-1.56 2.46-2.548l-.047-.02z"/></svg>
                        </a>
                        <a class="link" href="#" data-tippy-content="@github_handle">
                            <svg class="h-6 fill-current text-gray-600 hover:text-green-700" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>GitHub</title><path d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"/></svg>
                        </a>
                        <a class="link" href="#" data-tippy-content="@unsplash_handle">
                            <svg class="h-6 fill-current text-gray-600 hover:text-green-700" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Unsplash</title><path d="M7.5 6.75V0h9v6.75h-9zm9 3.75H24V24H0V10.5h7.5v6.75h9V10.5z"/></svg>
                        </a>
                        <a class="link" href="#" data-tippy-content="@dribble_handle">
                            <svg class="h-6 fill-current text-gray-600 hover:text-green-700" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Dribbble</title><path d="M12 24C5.385 24 0 18.615 0 12S5.385 0 12 0s12 5.385 12 12-5.385 12-12 12zm10.12-10.358c-.35-.11-3.17-.953-6.384-.438 1.34 3.684 1.887 6.684 1.992 7.308 2.3-1.555 3.936-4.02 4.395-6.87zm-6.115 7.808c-.153-.9-.75-4.032-2.19-7.77l-.066.02c-5.79 2.015-7.86 6.025-8.04 6.4 1.73 1.358 3.92 2.166 6.29 2.166 1.42 0 2.77-.29 4-.814zm-11.62-2.58c.232-.4 3.045-5.055 8.332-6.765.135-.045.27-.084.405-.12-.26-.585-.54-1.167-.832-1.74C7.17 11.775 2.206 11.71 1.756 11.7l-.004.312c0 2.633.998 5.037 2.634 6.855zm-2.42-8.955c.46.008 4.683.026 9.477-1.248-1.698-3.018-3.53-5.558-3.8-5.928-2.868 1.35-5.01 3.99-5.676 7.17zM9.6 2.052c.282.38 2.145 2.914 3.822 6 3.645-1.365 5.19-3.44 5.373-3.702-1.81-1.61-4.19-2.586-6.795-2.586-.825 0-1.63.1-2.4.285zm10.335 3.483c-.218.29-1.935 2.493-5.724 4.04.24.49.47.985.68 1.486.08.18.15.36.22.53 3.41-.43 6.8.26 7.14.33-.02-2.42-.88-4.64-2.31-6.38z"/></svg>
                        </a>
                        <a class="link" href="#" data-tippy-content="@instagram_handle">
                            <svg class="h-6 fill-current text-gray-600 hover:text-green-700" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Instagram</title><path d="M12 0C8.74 0 8.333.015 7.053.072 5.775.132 4.905.333 4.14.63c-.789.306-1.459.717-2.126 1.384S.935 3.35.63 4.14C.333 4.905.131 5.775.072 7.053.012 8.333 0 8.74 0 12s.015 3.667.072 4.947c.06 1.277.261 2.148.558 2.913.306.788.717 1.459 1.384 2.126.667.666 1.336 1.079 2.126 1.384.766.296 1.636.499 2.913.558C8.333 23.988 8.74 24 12 24s3.667-.015 4.947-.072c1.277-.06 2.148-.262 2.913-.558.788-.306 1.459-.718 2.126-1.384.666-.667 1.079-1.335 1.384-2.126.296-.765.499-1.636.558-2.913.06-1.28.072-1.687.072-4.947s-.015-3.667-.072-4.947c-.06-1.277-.262-2.149-.558-2.913-.306-.789-.718-1.459-1.384-2.126C21.319 1.347 20.651.935 19.86.63c-.765-.297-1.636-.499-2.913-.558C15.667.012 15.26 0 12 0zm0 2.16c3.203 0 3.585.016 4.85.071 1.17.055 1.805.249 2.227.415.562.217.96.477 1.382.896.419.42.679.819.896 1.381.164.422.36 1.057.413 2.227.057 1.266.07 1.646.07 4.85s-.015 3.585-.074 4.85c-.061 1.17-.256 1.805-.421 2.227-.224.562-.479.96-.899 1.382-.419.419-.824.679-1.38.896-.42.164-1.065.36-2.235.413-1.274.057-1.649.07-4.859.07-3.211 0-3.586-.015-4.859-.074-1.171-.061-1.816-.256-2.236-.421-.569-.224-.96-.479-1.379-.899-.421-.419-.69-.824-.9-1.38-.165-.42-.359-1.065-.42-2.235-.045-1.26-.061-1.649-.061-4.844 0-3.196.016-3.586.061-4.861.061-1.17.255-1.814.42-2.234.21-.57.479-.96.9-1.381.419-.419.81-.689 1.379-.898.42-.166 1.051-.361 2.221-.421 1.275-.045 1.65-.06 4.859-.06l.045.03zm0 3.678c-3.405 0-6.162 2.76-6.162 6.162 0 3.405 2.76 6.162 6.162 6.162 3.405 0 6.162-2.76 6.162-6.162 0-3.405-2.76-6.162-6.162-6.162zM12 16c-2.21 0-4-1.79-4-4s1.79-4 4-4 4 1.79 4 4-1.79 4-4 4zm7.846-10.405c0 .795-.646 1.44-1.44 1.44-.795 0-1.44-.646-1.44-1.44 0-.794.646-1.439 1.44-1.439.793-.001 1.44.645 1.44 1.439z"/></svg>
                        </a>
                        <a class="link" href="#" data-tippy-content="@youtube_handle">
                            <svg class="h-6 fill-current text-gray-600 hover:text-green-700" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>YouTube</title><path d="M23.495 6.205a3.007 3.007 0 0 0-2.088-2.088c-1.87-.501-9.396-.501-9.396-.501s-7.507-.01-9.396.501A3.007 3.007 0 0 0 .527 6.205a31.247 31.247 0 0 0-.522 5.805 31.247 31.247 0 0 0 .522 5.783 3.007 3.007 0 0 0 2.088 2.088c1.868.502 9.396.502 9.396.502s7.506 0 9.396-.502a3.007 3.007 0 0 0 2.088-2.088 31.247 31.247 0 0 0 .5-5.783 31.247 31.247 0 0 0-.5-5.805zM9.609 15.601V8.408l6.264 3.602z"/></svg>
                        </a>
                    </div>
                </div>
            </div>
            {% if user.user_profile.profile_picture %}
                <div class="w-full lg:w-2/5">
                    <img src="/media/{{user.user_profile.profile_picture}}" class="rounded-none lg:rounded-lg shadow-2xl hidden lg:block">
                    <button class="btn btn-blue bg-white-500">
                        <a href="{% url 'app_auth:change_pro_pic' %}" class="bg-gray-500 p-3" >
                            Change Profile Picture
                        </a>
                    </button>
                </div>
            {% else %}
                <div class="w-full lg:w-2/5">
                    <img src="https://t4.ftcdn.net/jpg/03/32/59/65/360_F_332596535_lAdLhf6KzbW6PWXBWeIFTovTii1drkbT.jpg" class="rounded-none lg:rounded-lg shadow-2xl hidden lg:block">
                    <button class="btn btn-blue bg-white-500">
                        <a href="{% url 'app_auth:add_pro_pic' %}" class="bg-gray-500 p-3" >
                            Add Profile Picture
                        </a>
                    </button>
                </div>
            {% endif %}
        </div>
        
    </div>

{% endblock content %}

app_auth/templates/app_auth/signup.html
{% extends 'auth_base.html' %}
{% load tailwind_filters %}
{% block title %}Create New Account{% endblock title %}
{% block content %}
    {% if registered %}
        <div class="bg-green-100 border border-green-400 text-black-700 px-4 py-3 rounded relative mx-7" role="alert">
            <strong class="font-bold">Account Created</strong>
            <span class="block sm:inline">
                Login Now by 
                <a href="{% url 'app_auth:login' %}">
                    <button class="bg-purple-500 hover:bg-blue-700 text-white font-bold py-1 px-2 rounded">
                        Clicking here
                    </button>
                </a>
            </span>
            <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
                <svg class="fill-current h-6 w-6 text-red-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
            </span>
        </div>
    {% else %}
        <div class="min-h-screen flex flex-col mb-4">
            <div class="container max-w-sm mx-auto flex-1 flex flex-col items-center justify-center px-2">
                <div class="bg-gray-100 px-3 rounded shadow-md text-black-900 w-full">
                    <h1 class="mb-8 text-3xl text-center">Sign up</h1>
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button
                        type="submit"
                        class="w-full text-center py-1 rounded bg-pink-400 hover:bg-pink-600 focus:outline-none my-1"
                        >Create Account</button>
                    </form>

                    <div class="text-center text-sm text-grey-dark my-2">
                        By signing up, you agree to the 
                        <a class="no-underline border-b border-grey-dark text-grey-dark" href="">
                            Terms of Service
                        </a> and 
                        <a class="no-underline border-b border-grey-dark text-grey-dark" href="">
                            Privacy Policy
                        </a>
                        <div class="text-grey-dark mt-2">
                            Already have an account? 
                            <a href="{% url 'app_auth:login' %}">
                                <button class="bg-purple-500 hover:bg-blue-700 text-white font-bold py-1 px-2 rounded">
                                    Login
                                </button>
                            </a>
                        </div>
                        <div class="text-grey-dark mt-2">
                            Back to
                            <a href="{% url 'app_post:post_list' %}">
                                <button class="bg-green-500 hover:bg-blue-700 text-white font-bold py-1 px-2 rounded">
                                    Home
                                </button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock content %}