MyBlogMain/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('app_auth.urls')),
    path('', include('app_post.urls')),
    path('like/', include('app_like.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_auth/urls.py
from django.urls import path
from .views import change_pro_pic, login_page, logout_user, pass_change, profile, sign_up_view, user_change

app_name = "app_auth"

urlpatterns = [
    path('signup/', sign_up_view, name="signup"),
    path('login/', login_page, name='login'),
    path('logout/', logout_user, name='logout'),
    path('profile/', profile, name='profile'),
    path('change-profile/', user_change, name='user_change'),
    path('password/', pass_change, name='pass_change'),
    path('add-picture/', change_pro_pic, name='add_pro_pic'),
    path('change-picture/', change_pro_pic, name='change_pro_pic'),
]

app_like/urls.py
from django.urls import path
from .views import liked, unliked


app_name = "app_like"
urlpatterns = [
    path('liked/<pk>/', liked, name='liked_post'),
    path('unliked/<pk>/', unliked, name='unliked_post'),
]

app_post/urls.py
from .views import CreatePost, MyPosts, UpdatePost, post_details, PostList
from django.urls import path

app_name="app_post"

urlpatterns = [
    path('', PostList.as_view(), name='post_list'),
    path('details/<slug:slug>', post_details, name='post_details'),
    path('write/', CreatePost.as_view(), name='create_post'),
    path('my-blogs/', MyPosts.as_view(), name='my_blogs'),
    path('edit/<pk>/', UpdatePost.as_view(), name='edit_blog'),
]

app_post/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.
User = get_user_model()


class Post(models.Model):
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='post_author')
    blog_title = models.CharField(max_length=264, verbose_name="Put a Title")
    slug = models.SlugField(max_length=264, unique=True)
    blog_content = models.TextField(verbose_name="What is on your mind?")
    blog_image = models.ImageField(
        upload_to='blog_images', verbose_name="Image")
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-publish_date', ]

    def __str__(self):
        return f"{self.author} {self.blog_title}"

app_post/views.py
from .permissions import LoginRequiredandAuthorMixin
from django.views.generic.edit import UpdateView
from app_like.models import Like
from django.shortcuts import render
from django.views.generic import ListView, CreateView, TemplateView
from .models import Post
from django.contrib.auth.decorators import login_required
from app_comment.forms import CommentForm
from django.http.response import HttpResponseRedirect
from django.urls.base import reverse, reverse_lazy
from django.contrib.auth.mixins import AccessMixin, LoginRequiredMixin
import uuid
from slugify import slugify

# Create your views here.


class PostList(ListView):
    context_object_name = 'posts'
    model = Post
    paginate_by = 8
    template_name = 'app_post/post_list.html'


@login_required
def post_details(request, slug):
    post = Post.objects.get(slug=slug)
    comment_form = CommentForm()
    already_liked = Like.objects.filter(post=post, user=request.user)
    if already_liked:
        liked = True
    else:
        liked = False
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.post = post
            comment.save()
            return HttpResponseRedirect(reverse('app_post:post_details', kwargs={'slug': slug}))
    return render(request, 'app_post/post_details.html', context={'post': post, 'comment_form': comment_form, 'liked': liked, })


class CreatePost(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'app_post/create_post.html'
    fields = ('blog_title', 'blog_content', 'blog_image',)

    def form_valid(self, form):
        post_object = form.save(commit=False)
        post_object.author = self.request.user
        title = post_object.blog_title
        post_object.slug = slugify(title+str(uuid.uuid4()))
        post_object.save()
        return HttpResponseRedirect(reverse('app_post:post_list'))


class MyPosts(LoginRequiredMixin, TemplateView):
    template_name = 'app_post/my_posts.html'


class UpdatePost(LoginRequiredandAuthorMixin, UpdateView):
    model = Post
    fields = ('blog_title', 'blog_content', 'blog_image')
    template_name = 'app_post/edit_post.html'

    def get_success_url(self, **kwargs):
        return reverse_lazy('app_post:post_details', kwargs={'slug': self.object.slug})

app_post/templates/app_post/create_post.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block title %}Create a Post{% endblock title %}
{% block content %}
    <div class="mx-20">
        <h2>Write Your Post Here:</h2>
        <form method="POST" enctype="multipart/form-data">
            {{ form|crispy }}
            {% csrf_token %}
            <button type="submit" class="bg-green-500 hover:bg-blue-700 text-white font-bold py-1 px-2 rounded">Publish</button>
        </form>
    </div>
{% endblock content %}

app_post/templates/app_post/edit_post.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block title %}Update Post{% endblock title %}
{% block content %}
    <div class="mx-20">
        <h2>Edit Your Post Here:</h2>
        <form method="POST" enctype="multipart/form-data">
            {{ form|crispy }}
            {% csrf_token %}
            <button type="submit" class="bg-green-500 hover:bg-blue-700 text-white font-bold py-1 px-2 rounded">Update</button>
        </form>
    </div>
{% endblock content %}

app_post/templates/app_post/my_posts.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title %} {{ user }} {% endblock title %}
{% block content %}
    <section class="text-gray-600 body-font">
        <div class="container px-5 py-10 mx-auto">
            <div class="flex flex-wrap -m-4">

                {% for post in user.post_author.all %}
                    <div class="p-4 md:w-1/3">
                        <div class="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden">
                            <img class="lg:h-48 md:h-36 w-full object-cover object-center" src="/media/{{post.blog_image}}" alt="blog">
                            <div class="p-6">
                                <h2 class="tracking-widest text-xs title-font font-medium text-gray-400 mb-1">
                                    CATEGORY
                                    <i>{{post.publish_date}}</i>
                                </h2>
                                <h1 class="title-font text-lg font-medium text-gray-900 mb-1">
                                    {{ post.blog_title }}
                                </h1>
                                <h2 class="tracking-widest text-xs title-font font-medium text-pink-700 mb-1">
                                    <i>Posted By: @{{post.author}}</i>
                                </h2>
                                <p class="leading-relaxed mb-3">
                                    {{post.blog_content|range_filter|linebreaks}}
                                </p>
                                <div class="flex items-center flex-wrap ">
                                    <a href="{% url 'app_post:post_details' slug=post.slug %}" class="text-indigo-500 inline-flex items-center md:mb-2 lg:mb-0">Read More
                                        <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                            <path d="M5 12h14"></path>
                                            <path d="M12 5l7 7-7 7"></path>
                                        </svg>
                                    </a>
                                    <span class="text-gray-400 mr-3 inline-flex items-center lg:ml-auto md:ml-0 ml-auto leading-none text-sm pr-3 py-1 border-r-2 border-gray-200">
                                        <svg class="w-4 h-4 mr-1" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" viewBox="0 0 24 24">
                                            <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
                                            <circle cx="12" cy="12" r="3"></circle>
                                        </svg>
                                        {{post.liked_blog.count}}
                                    </span>
                                    <span class="text-gray-400 inline-flex items-center leading-none text-sm">
                                        <svg class="w-4 h-4 mr-1" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" viewBox="0 0 24 24">
                                        <path d="M21 11.5a8.38 8.38 0 01-.9 3.8 8.5 8.5 0 01-7.6 4.7 8.38 8.38 0 01-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 01-.9-3.8 8.5 8.5 0 014.7-7.6 8.38 8.38 0 013.8-.9h.5a8.48 8.48 0 018 8v.5z"></path>
                                        </svg>{{post.blog_comment.count }}
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            {% if page_obj.has_previous or page_obj.has_next %}
                <div class="pagination my-4">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page=1" class="bg-yellow-500 hover:bg-blue-700 text-white font-bold py-1 px-2 rounded">&laquo; first</a>
                            <a href="?page={{ page_obj.previous_page_number }}" class="bg-pink-500 hover:bg-blue-700 text-white font-bold py-1 px-2 rounded">previous</a>
                        {% endif %}

                        <span class="current font-bold">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>

                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}" class="bg-green-500 hover:bg-blue-700 text-white font-bold py-1 px-2 rounded">next</a>
                            <a href="?page={{ page_obj.paginator.num_pages }}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-1 px-2 rounded">last &raquo;</a>
                        {% endif %}
                    </span>
                </div>
            {% endif %}
        </div>
    </section>
{% endblock content %}

app_post/templates/app_post/post_details.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block title %} {{ post.blog_title }} {% endblock title %}
{% block content %}
	<div class="max-w-screen-lg mx-auto">
    <main class="mt-10">

      <div class="mb-4 md:mb-0 w-full mx-auto relative">
        <div class="px-4 lg:px-0">
          <h2 class="text-4xl font-semibold text-gray-800 leading-tight">
            {{ post.blog_title }}
          </h2>
          <a 
            href="#"
            class="bg-yellow-100 hover:bg-yellow-300 p-1 px-2 text-green-700 inline-flex items-center justify-center"
          >
            Cryptocurrency
          </a>
          {% if post.author == user %}
            <a href="{% url 'app_post:edit_blog' pk=post.pk %}" class="bg-yellow-100 hover:bg-yellow-300 p-1 px-2 text-green-700 inline-flex items-center justify-center">
              Edit
            </a>
          {% endif %}
          <h2 class="tracking-widest text-xs title-font font-medium text-gray-400 my-2">
              <i>Posted on: {{post.publish_date}} &nbsp;&nbsp;&nbsp;&nbsp; Updated on: {{post.update_date}}</i>
          </h2>
        </div>

        <img src="/media/{{post.blog_image}}" class="w-full object-cover lg:rounded" style="height: 28em;"/>
      </div>

      <div class="flex flex-col lg:flex-row lg:space-x-12">

        <div class="px-4 lg:px-0 mt-12 text-gray-700 text-lg leading-relaxed w-full lg:w-3/4">
          <p class="pb-6">
            {{post.blog_content|linebreaks}}
          </p>
        </div>

        <div class="w-full lg:w-1/4 m-auto mt-12 max-w-screen-sm">
          <div class="p-4 border-t border-b md:border md:rounded">
            <div class="flex py-2">
              {% if post.author.user_profile.profile_picture %}
                <img src="/media/{{ post.author.user_profile.profile_picture }}" class="h-10 w-10 rounded-full mr-2 object-cover" />
              {% else %}
                <img src="https://cdn1.iconfinder.com/data/icons/technology-devices-2/100/Profile-512.png" class="h-10 w-10 rounded-full mr-2 object-cover" />
              {% endif %}
              <div>
                <p class="font-semibold text-gray-700 text-sm">
                  {% if post.author.first_name and post.author.last_name %}
                      {{post.author.first_name }} {{ post.author.last_name }}
                  {% else %}
                      @{{ post.author.username }}
                  {% endif %}
                </p>
                <p class="font-semibold text-gray-600 text-xs"> Editor </p>
              </div>
            </div>
            <p class="text-gray-700 py-3">
              Mike writes about technology
              Yourself required no at thoughts delicate landlord it be. Branched dashwood do is whatever it.
            </p>
            <button class="px-2 py-1 text-gray-100 bg-green-700 flex w-full items-center justify-center rounded">
              Follow 
              <i class='bx bx-user-plus ml-2' ></i>
            </button>
          </div>
        </div>

      </div>
    </main>
    <div class="my-2">
      {% if not liked %}
        <a href="{% url 'app_like:liked_post' pk=post.pk %}">
          <i class="fa fa-thumbs-up fa-2x"></i>
        </a>
      {% else %}
        <a href="{% url 'app_like:unliked_post' pk=post.pk %}">
          <i class="fa fa-thumbs-down fa-2x"></i>
        </a>
      {% endif %}
    </div>
    <section class="rounded-b-lg  mt-4 ">
      <form action="" accept-charset="UTF-8" method="post">
        {{ comment_form|crispy }}
        {% csrf_token %}
        <button type="submit" class="font-bold py-2 px-4 w-full bg-purple-400 text-lg text-white shadow-md rounded-lg">Comment</button>
      </form>
      <div id="task-comments" class="pt-4">
        {% for comment in post.blog_comment.all %}
          <div class="bg-white rounded-lg p-3  flex flex-col justify-center items-center md:items-start shadow-lg mb-4">
            <div class="flex flex-row justify-center mr-2">
              {% if comment.user.user_profile.profile_picture %}
                <img alt="avatar" width="48" height="48" class="rounded-full w-10 h-10 mr-4 shadow-lg mb-4" src="/media/{{comment.user.user_profile.profile_picture}}">
              {% else %} 
                <img alt="avatar" width="48" height="48" class="rounded-full w-10 h-10 mr-4 shadow-lg mb-4" src="https://cdn1.iconfinder.com/data/icons/technology-devices-2/100/Profile-512.png">               
              {% endif %}
              <h3 class="text-purple-600 font-semibold text-lg text-center md:text-left ">
                {% if comment.user.first_name and comment.user.last_name %}
                  {{comment.user.first_name }} {{ comment.user.last_name }}
                {% else %}
                  @{{ comment.user.username }}
                {% endif %}
              </h3>
            </div>
            <p style="width: 90%" class="text-gray-600 text-lg text-center md:text-left ">
              {{comment.comment}}
            </p>
          </div>
        {% endfor %}
      </div>
    </section>
  </div>
{% endblock content %}

app_post/templates/app_post/post_list.html
{% extends 'base.html' %}
{% block title %}Home{% endblock title %}
{% load tailwind_filters %}
{% load custom_filters %}
{% block content %}
    {% include 'hero.html' %}
    <section class="text-gray-600 body-font">
        <div class="container px-5 py-10 mx-auto">
            <div class="flex flex-wrap -m-4">

                {% for post in posts %}
                    <div class="p-4 md:w-1/3">
                        <div class="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden">
                            <img class="lg:h-48 md:h-36 w-full object-cover object-center" src="/media/{{post.blog_image}}" alt="blog">
                            <div class="p-6">
                                <h2 class="tracking-widest text-xs title-font font-medium text-gray-400 mb-1">
                                    CATEGORY
                                    <i>{{post.publish_date}}</i>
                                </h2>
                                <h1 class="title-font text-lg font-medium text-gray-900 mb-1">
                                    {{ post.blog_title }}
                                </h1>
                                <h2 class="tracking-widest text-xs title-font font-medium text-pink-700 mb-1">
                                    <i>Posted By: @{{post.author}}</i>
                                </h2>
                                <p class="leading-relaxed mb-3">
                                    {{post.blog_content|range_filter|linebreaks}}
                                </p>
                                <div class="flex items-center flex-wrap ">
                                    <a href="{% url 'app_post:post_details' slug=post.slug %}" class="text-indigo-500 inline-flex items-center md:mb-2 lg:mb-0">Read More
                                        <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                            <path d="M5 12h14"></path>
                                            <path d="M12 5l7 7-7 7"></path>
                                        </svg>
                                    </a>
                                    <span class="text-gray-400 mr-3 inline-flex items-center lg:ml-auto md:ml-0 ml-auto leading-none text-sm pr-3 py-1 border-r-2 border-gray-200">
                                        <svg class="w-4 h-4 mr-1" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" viewBox="0 0 24 24">
                                            <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
                                            <circle cx="12" cy="12" r="3"></circle>
                                        </svg>
                                        {{post.liked_blog.count}}
                                    </span>
                                    <span class="text-gray-400 inline-flex items-center leading-none text-sm">
                                        <svg class="w-4 h-4 mr-1" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" viewBox="0 0 24 24">
                                        <path d="M21 11.5a8.38 8.38 0 01-.9 3.8 8.5 8.5 0 01-7.6 4.7 8.38 8.38 0 01-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 01-.9-3.8 8.5 8.5 0 014.7-7.6 8.38 8.38 0 013.8-.9h.5a8.48 8.48 0 018 8v.5z"></path>
                                        </svg>{{post.blog_comment.count }}
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="pagination my-4">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1" class="bg-yellow-500 hover:bg-blue-700 text-white font-bold py-1 px-2 rounded">&laquo; first</a>
                        <a href="?page={{ page_obj.previous_page_number }}" class="bg-pink-500 hover:bg-blue-700 text-white font-bold py-1 px-2 rounded">previous</a>
                    {% endif %}

                    <span class="current font-bold">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}" class="bg-green-500 hover:bg-blue-700 text-white font-bold py-1 px-2 rounded">next</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-1 px-2 rounded">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </section>
{% endblock content %}